### ISSUE TITLE
Criar página com "Código de Conduta"

### ISSUE THREAD

**Issue by fabriziomello** [pgbr/www-2015#25]
Criar um item "Código de Conduta":

O PGBR é um evento que ocorre desde 2007. Em todos estes anos
procuramos manter uma conduta de respeito a todos os participantes,
palestrantes, organizadores, prestadores de serviços e patrocinadores
e nesta edição de 2015 não será diferente.

Nos dedicaremos para que todos tenham uma experiência livre de
assédios e discriminação. Não serão tolerados assédios ou
descriminação de qualquer tipo a qualquer um dos participantes.
Podemos incluir como assédio comentários ofensivos relacionado a
gênero, deficiências, orientação sexual, aparência física, raça,
religião, bem como, contato físico inapropriado, perseguições,
fotografia ou filmagem assediante, linguagem ou imagens de conotação
sexual. Consideramos isso inapropriado para uma conferência.
Participantes que sejam solicitados a pararem como assédio deverão
fazê-lo imediatamente, caso contrário estarão sujeitos a expulsão do
evento ou encaminhamento as autoridades cabíveis.

Qualquer voluntário da organização estará disponível a auxiliar
participantes que se sintam assediados a contactar as autoridades
cabíveis.

Como participante do evento, seja você palestrante, voluntário,
organizador, patrocinador deverá aceitar e respeitar nosso código de
conduta.

Ps: em seguida envio a versão em en-us

**Comment by nbluis** [comment]
@guedes

**Comment by guedes** [comment]
Caros, desculpe pela demora. Segue a versão em inglês, que pode ter alguns erros:

The PGBR is a conference taking place since 2007. In all these years
We maintained a conduct of respect to all participants,
speakers, organizers, service providers and sponsors
and this edition of 2015 will be no different.

We will be dedicated to everyone to have an experience free of
harassment and discrimination. No harassment or discrimination of any
kind to any of the participants will be tolerated. By harassment we
man offensive comments related to gender, disability, sexual
orientation, physical appearance, race, religion as well as
inappropriate physical contact, photograph or harassing filming,
language or connotation of sexual images. We consider it inappropriate
for a conference. Participants asked to stop such harassment should do
it immediately, otherwise they will be subject to expulsion from the
event or sent to appropriate authorities.

Any volunteer from the organization will be available to assist
participants who feel harassed, to contact the appropriate
authorities.

As a conference participant, whether you are a speaker, volunteer,
organizer, sponsor, etc., must accept and respect our code of conduct.

**Comment by guedes** [comment]
Caros o código de conduta enviado pelo G. Elias parece mais claro e completo ao meu ver, o que acham de [1]? E tem a versão já em inglês em [2].

[1] https://github.com/confcodeofconduct/confcodeofconduct.com/blob/master/index-pt-br.html
[2] https://github.com/confcodeofconduct/confcodeofconduct.com/blob/master/index.html

**Comment by nbluis** [comment]
Eu acho joia @guedes, faço o link direto pra eles agora a noite.

**Comment by nbluis** [comment]
Done
